[Application]
FileLogger\Age=3
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs

[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddTorrentStopped=false
Session\AlternativeGlobalDLSpeedLimit=1000000
Session\AlternativeGlobalUPSpeedLimit=100
Session\AnonymousModeEnabled=false
Session\BandwidthSchedulerEnabled=true
Session\DHTEnabled=false
Session\DefaultSavePath=/data/completed
Session\Encryption=0
Session\ExcludedFileNames=
Session\GlobalDLSpeedLimit=0
Session\GlobalUPSpeedLimit=0
Session\Interface=
Session\InterfaceName=
Session\LSDEnabled=false
Session\MaxActiveDownloads=7
Session\MaxActiveTorrents=2000
Session\MaxActiveUploads=2000
Session\PeXEnabled=false
Session\Port=34566
Session\QueueingSystemEnabled=true
Session\SSL\Port=56659
Session\ShareLimitAction=Stop
Session\Tags=cross-seed
Session\TempPath=/data/incomplete
Session\TempPathEnabled=true
Session\UseAlternativeGlobalSpeedLimit=false

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\Locale=en
General\StatusbarExternalIPDisplayed=true
MailNotification\req_auth=true
Scheduler\end_time=@Variant(\0\0\0\xf\x1\xee\x62\x80)
Scheduler\start_time=@Variant(\0\0\0\xf\x4\x13\xb3\x80)
WebUI\Address=*
WebUI\AuthSubnetWhitelist=127.0.0.1/32
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\HostHeaderValidation=false
WebUI\MaxAuthenticationFailCount=3
WebUI\Password_PBKDF2="<to be defined>"
WebUI\Port=8080
WebUI\ServerDomains=*

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
