services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: ${PUID}:${PGID}
    networks: [net-chill]
    volumes:
      - ${recyconfig}:/config
    environment:
      - TZ=${TZ}

networks:
  net-chill:
    name: net-chill
    external: true

