version: '3.9'
services:
  jellyhookapi:
    container_name: jellyhookapi
    restart: always
    build: .
    ports:
      - "0.0.0.0:7777:7777"
    networks:
      net-chill:
        ipv4_address: 10.10.66.199

networks:
  net-chill:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.66.0/24

